from __future__ import annotations

from dataclasses import dataclass

from app.core.capabilities.models import (
    CapabilityActivationMode as Mode,
    CapabilityCategory as Category,
    CapabilityCriticality as Criticality,
    CapabilityDescriptor,
    CapabilityResourceProfile as Resource,
    CapabilityState,
)
from app.core.capabilities.registry import CapabilityRegistry, get_capability_registry


@dataclass(frozen=True)
class DefaultCapability:
    descriptor: CapabilityDescriptor
    initial_state: CapabilityState
    initial_reason: str


def _descriptor(
    *,
    capability_id: str,
    name: str,
    category: Category,
    criticality: Criticality,
    activation_mode: Mode,
    dependencies: list[str] | None = None,
    description: str,
    owner: str,
    resource_profile: list[Resource] | None = None,
    config_key: str | None = None,
    component_path: str | None = None,
    metadata: dict | None = None,
) -> CapabilityDescriptor:
    return CapabilityDescriptor(
        id=capability_id,
        name=name,
        category=category,
        criticality=criticality,
        activation_mode=activation_mode,
        dependencies=dependencies or [],
        description=description,
        owner=owner,
        resource_profile=resource_profile or [Resource.CPU_LIGHT],
        config_key=config_key,
        component_path=component_path,
        metadata=metadata or {},
    )


def _cold_reason() -> str:
    return "Registered as a core capability; awaiting managed activation."


def _startup_ready_reason() -> str:
    return "Registered during backend startup with a lightweight readiness check."


DEFAULT_CAPABILITIES: tuple[DefaultCapability, ...] = (
    DefaultCapability(
        _descriptor(
            capability_id="backend_api",
            name="Backend API",
            category=Category.SYSTEM,
            criticality=Criticality.FOUNDATIONAL,
            activation_mode=Mode.STARTUP,
            description="FastAPI application shell and route surface.",
            owner="backend/main.py",
            component_path="backend/main.py",
        ),
        CapabilityState.READY,
        _startup_ready_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="frontend_api_contract",
            name="Frontend API Contract",
            category=Category.FRONTEND_API,
            criticality=Criticality.FOUNDATIONAL,
            activation_mode=Mode.STARTUP,
            dependencies=["backend_api"],
            description="Frontend-to-backend API contract surface used by the command dashboard.",
            owner="frontend/src/api",
            component_path="frontend/src/api",
        ),
        CapabilityState.READY,
        _startup_ready_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="auth_session",
            name="Authentication Session",
            category=Category.AUTH,
            criticality=Criticality.FOUNDATIONAL,
            activation_mode=Mode.STARTUP,
            dependencies=["local_storage"],
            description="Operator authentication, session, cookie, and token lifecycle.",
            owner="backend/app/services/auth_service.py",
            config_key="security.auth",
            component_path="backend/app/services/auth_service.py",
            metadata={"config_path": "configs/runtime/security.yaml"},
        ),
        CapabilityState.READY,
        _startup_ready_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="rbac_permissions",
            name="RBAC Permissions",
            category=Category.AUTH,
            criticality=Criticality.FOUNDATIONAL,
            activation_mode=Mode.STARTUP,
            dependencies=["auth_session"],
            description="Role-based permission model for operator and supervisor actions.",
            owner="backend/app/security/permissions.py",
            config_key="security.rbac",
            component_path="backend/app/security/permissions.py",
            metadata={"config_path": "configs/runtime/security.yaml"},
        ),
        CapabilityState.READY,
        _startup_ready_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="local_storage",
            name="Local Storage",
            category=Category.STORAGE,
            criticality=Criticality.FOUNDATIONAL,
            activation_mode=Mode.STARTUP,
            description="Local-first file, JSONL, evidence, and runtime state storage.",
            owner="backend/app/core/persistence.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            component_path="backend/app/core/persistence.py",
            metadata={"writable_paths": ["storage", "runtime_state", "logs"]},
        ),
        CapabilityState.READY,
        _startup_ready_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="runtime_health",
            name="Runtime Health",
            category=Category.SYSTEM,
            criticality=Criticality.FOUNDATIONAL,
            activation_mode=Mode.STARTUP,
            dependencies=["backend_api", "local_storage"],
            description="Runtime health, liveness, readiness, and operator visibility surface.",
            owner="backend/app/services/runtime_health_service.py",
            component_path="backend/app/services/runtime_health_service.py",
        ),
        CapabilityState.READY,
        _startup_ready_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="uploaded_video_pipeline",
            name="Uploaded Video Pipeline",
            category=Category.VIDEO_INTELLIGENCE,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.JOB_TRIGGERED,
            dependencies=["local_storage", "yolo_weapon_detector", "yolo_phone_detector", "tracking_engine", "event_engine"],
            description="Uploaded video ingestion, frame processing, event generation, and report data production.",
            owner="backend/app/services/uploaded_video_service.py",
            resource_profile=[Resource.CPU_HEAVY, Resource.GPU_HEAVY, Resource.FILE_IO],
            config_key="uploaded_video",
            component_path="backend/app/services/uploaded_video_service.py",
            metadata={"config_path": "configs/runtime/uploaded_video.yaml", "enabled_path": "uploaded_video.enabled"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="live_stream_pipeline",
            name="Live Stream Pipeline",
            category=Category.STREAMING,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["yolo_weapon_detector", "yolo_phone_detector", "tracking_engine", "event_engine"],
            description="Live video stream ingestion, session lifecycle, frame processing, and operator feeds.",
            owner="backend/app/api/streaming_routes.py",
            resource_profile=[Resource.CPU_HEAVY, Resource.GPU_HEAVY, Resource.NETWORK_IO],
            config_key="streaming",
            component_path="backend/app/api/streaming_routes.py",
            metadata={"config_path": "configs/runtime/streaming.yaml"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="yolo_weapon_detector",
            name="YOLO Weapon Detector",
            category=Category.ML_MODEL,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.PREFLIGHT,
            dependencies=["model_governance"],
            description="Weapon-related object detector selected through the governed model registry.",
            owner="inference/detection_engine.py",
            resource_profile=[Resource.GPU_HEAVY, Resource.CPU_HEAVY],
            config_key="model_registry.weapon",
            component_path="inference/detection_engine.py",
            metadata={"required_paths": ["models/registry.json"]},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="yolo_phone_detector",
            name="YOLO Phone Detector",
            category=Category.ML_MODEL,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.PREFLIGHT,
            dependencies=["model_governance"],
            description="Phone/device detector selected through the governed model registry.",
            owner="inference/detection_engine.py",
            resource_profile=[Resource.GPU_HEAVY, Resource.CPU_HEAVY],
            config_key="model_registry.phone",
            component_path="inference/detection_engine.py",
            metadata={"required_paths": ["models/registry.json"]},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="tracking_engine",
            name="Tracking Engine",
            category=Category.ML_RUNTIME,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.JOB_TRIGGERED,
            dependencies=["yolo_weapon_detector", "yolo_phone_detector"],
            description="Multi-object tracking and track lifecycle runtime.",
            owner="inference/tracker.py",
            resource_profile=[Resource.CPU_HEAVY],
            component_path="inference/tracker.py",
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="event_engine",
            name="Event Engine",
            category=Category.EVENT_INTELLIGENCE,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.JOB_TRIGGERED,
            dependencies=["tracking_engine"],
            description="Threat/event derivation from detections, tracks, and temporal buffers.",
            owner="inference/event_engine.py",
            component_path="inference/event_engine.py",
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="scenario_engine",
            name="Scenario Engine",
            category=Category.EVENT_INTELLIGENCE,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.JOB_TRIGGERED,
            dependencies=["event_engine"],
            description="Scenario aggregation and operational context enrichment.",
            owner="inference/scenario_engine.py",
            component_path="inference/scenario_engine.py",
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="drone_simulation",
            name="Drone Simulation",
            category=Category.DRONE_SIMULATION,
            criticality=Criticality.EXTERNAL_DEPENDENT,
            activation_mode=Mode.PREFLIGHT,
            dependencies=["gis_map", "drone_telemetry"],
            description="Cosys/AirSim-backed simulated aerial observation runtime.",
            owner="backend/app/services/drone/drone_simulation_service.py",
            resource_profile=[Resource.EXTERNAL_SERVICE, Resource.NETWORK_IO, Resource.CPU_HEAVY],
            config_key="drone_simulation",
            component_path="backend/app/services/drone/drone_simulation_service.py",
            metadata={"config_path": "configs/runtime/drone_simulation.yaml", "enabled_path": "drone_simulation.enabled"},
        ),
        CapabilityState.COLD,
        "Registered as an external-dependent core capability; simulator connection awaits managed activation.",
    ),
    DefaultCapability(
        _descriptor(
            capability_id="drone_mission_planner",
            name="Drone Mission Planner",
            category=Category.DRONE_MISSION,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["drone_simulation", "gis_map"],
            description="Mission planning, waypoint storage, and execution command surface.",
            owner="backend/app/api/drone_mission_routes.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            config_key="drone_mission",
            component_path="backend/app/api/drone_mission_routes.py",
            metadata={"config_path": "configs/runtime/drone_mission.yaml"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="drone_fusion",
            name="Drone Fusion",
            category=Category.DRONE_FUSION,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["drone_simulation", "drone_telemetry", "tracking_engine"],
            description="Cross-source drone and fixed-camera observation fusion.",
            owner="backend/app/api/drone_fusion_routes.py",
            resource_profile=[Resource.CPU_HEAVY, Resource.FILE_IO],
            config_key="drone_fusion",
            component_path="backend/app/api/drone_fusion_routes.py",
            metadata={"config_path": "configs/runtime/drone_fusion.yaml"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="drone_telemetry",
            name="Drone Telemetry",
            category=Category.DRONE_SIMULATION,
            criticality=Criticality.EXTERNAL_DEPENDENT,
            activation_mode=Mode.EXTERNAL_TRIGGERED,
            dependencies=["drone_simulation"],
            description="Telemetry capture and status updates from simulated drone runtime.",
            owner="backend/app/services/drone/drone_simulation_service.py",
            resource_profile=[Resource.EXTERNAL_SERVICE, Resource.NETWORK_IO],
            config_key="drone_simulation.telemetry",
            component_path="backend/app/services/drone/drone_simulation_service.py",
            metadata={"config_path": "configs/runtime/drone_simulation.yaml", "enabled_path": "drone_simulation.telemetry.enabled"},
        ),
        CapabilityState.COLD,
        "Registered as an external-dependent core capability; telemetry source awaits managed activation.",
    ),
    DefaultCapability(
        _descriptor(
            capability_id="drone_path_tracking",
            name="Drone Path Tracking",
            category=Category.DRONE_FUSION,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.JOB_TRIGGERED,
            dependencies=["drone_telemetry", "gis_map"],
            description="Drone flight path reconstruction and map overlay support.",
            owner="backend/app/services/path_reconstruction_service.py",
            resource_profile=[Resource.CPU_LIGHT, Resource.FILE_IO],
            component_path="backend/app/services/path_reconstruction_service.py",
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="alerts",
            name="Alerts",
            category=Category.EVENT_INTELLIGENCE,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.STARTUP,
            dependencies=["event_engine"],
            description="Operational alert queue, websocket broadcast, and review workflow.",
            owner="inference/alerts",
            component_path="inference/alerts",
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="incidents",
            name="Incidents",
            category=Category.EVENT_INTELLIGENCE,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["event_engine", "local_storage"],
            description="Incident records, replay linkage, and investigation event persistence.",
            owner="backend/app/models/incident_models.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            component_path="backend/app/models/incident_models.py",
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="cases",
            name="Cases",
            category=Category.CASE_MANAGEMENT,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["local_storage", "incidents"],
            description="Case management, assignment, review, and evidence linking.",
            owner="backend/app/services/case_service.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            config_key="case_management",
            component_path="backend/app/services/case_service.py",
            metadata={"config_path": "configs/runtime/case_management.yaml", "enabled_path": "case_management.enabled"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="evidence",
            name="Evidence",
            category=Category.EVIDENCE,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["cases", "local_storage"],
            description="Evidence files, metadata, integrity checks, and chain of custody support.",
            owner="backend/app/services/evidence_integrity.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            config_key="evidence",
            component_path="backend/app/services/evidence_integrity.py",
            metadata={"config_path": "configs/runtime/evidence.yaml"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="reports",
            name="Reports",
            category=Category.CASE_MANAGEMENT,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["cases", "evidence", "llm_osint"],
            description="Case exports, generated reports, and operator handoff artifacts.",
            owner="backend/app/services/case_export_service.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            component_path="backend/app/services/case_export_service.py",
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="analytics",
            name="Analytics",
            category=Category.ANALYTICS,
            criticality=Criticality.SUPPORTING,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["event_engine", "cases", "evidence"],
            description="Operational analytics, trends, source health, and export workflow.",
            owner="backend/app/services/analytics_service.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            config_key="analytics",
            component_path="backend/app/services/analytics_service.py",
            metadata={"config_path": "configs/runtime/analytics.yaml", "enabled_path": "analytics.enabled"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="anomaly_detection",
            name="Anomaly Detection",
            category=Category.ANOMALY,
            criticality=Criticality.MISSION_ADVANCED,
            activation_mode=Mode.PREFLIGHT,
            dependencies=["tracking_engine", "event_engine"],
            description="Rule, trajectory, scene, and video anomaly detection runtime.",
            owner="inference/anomaly",
            resource_profile=[Resource.GPU_HEAVY, Resource.CPU_HEAVY],
            config_key="anomaly",
            component_path="inference/anomaly",
            metadata={"config_path": "configs/runtime/anomaly.yaml", "enabled_path": "anomaly.enabled"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="open_vocab_detection",
            name="Open-Vocabulary Detection",
            category=Category.OPEN_VOCAB,
            criticality=Criticality.MISSION_ADVANCED,
            activation_mode=Mode.PREFLIGHT,
            dependencies=["live_stream_pipeline", "uploaded_video_pipeline"],
            description="Prompt-driven object and scene search using managed open-vocabulary model loading.",
            owner="inference/open_vocab",
            resource_profile=[Resource.GPU_HEAVY, Resource.CPU_HEAVY, Resource.FILE_IO],
            config_key="open_vocab",
            component_path="inference/open_vocab",
            metadata={"config_path": "configs/runtime/open_vocab.yaml", "enabled_path": "enabled"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="segmentation",
            name="Segmentation",
            category=Category.SEGMENTATION,
            criticality=Criticality.MISSION_ADVANCED,
            activation_mode=Mode.PREFLIGHT,
            dependencies=["yolo_weapon_detector", "yolo_phone_detector"],
            description="SAM2-backed segmentation and mask refinement for detections/events.",
            owner="inference/segmentation",
            resource_profile=[Resource.GPU_HEAVY, Resource.CPU_HEAVY],
            config_key="segmentation",
            component_path="inference/segmentation",
            metadata={
                "config_path": "configs/runtime/segmentation.yaml",
                "enabled_path": "segmentation.enabled",
                "required_paths": ["configs/runtime/segmentation.yaml", "configs/segmentation/sam2.yaml", "sam2_t.pt"],
            },
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="identity_reid",
            name="Identity / ReID",
            category=Category.IDENTITY,
            criticality=Criticality.MISSION_ADVANCED,
            activation_mode=Mode.PREFLIGHT,
            dependencies=["tracking_engine", "local_storage"],
            description="Identity candidates, face matching, ReID, calibration, and review support.",
            owner="backend/app/services/identity_service.py",
            resource_profile=[Resource.GPU_HEAVY, Resource.CPU_HEAVY, Resource.FILE_IO],
            config_key="identity",
            component_path="backend/app/services/identity_service.py",
            metadata={"config_path": "configs/runtime/identity.yaml", "enabled_path": "identity.enabled"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="model_governance",
            name="Model Governance",
            category=Category.MODEL_GOVERNANCE,
            criticality=Criticality.SUPPORTING,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["local_storage"],
            description="Model registry, limitations, drift, promotion, rollback, and governance checks.",
            owner="backend/app/services/model_governance_service.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            config_key="model_governance",
            component_path="backend/app/services/model_governance_service.py",
            metadata={
                "config_path": "configs/runtime/model_governance.yaml",
                "required_paths": ["models/registry.json"],
            },
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="gis_map",
            name="GIS Map",
            category=Category.GIS,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["local_storage"],
            description="GIS map, camera profiles, geofences, event overlays, and spatial context.",
            owner="backend/app/services/gis_service.py",
            resource_profile=[Resource.FILE_IO, Resource.NETWORK_IO, Resource.CPU_LIGHT],
            config_key="gis",
            component_path="backend/app/services/gis_service.py",
            metadata={"config_path": "configs/runtime/gis.yaml", "enabled_path": "gis.enabled"},
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="simulation_source_network",
            name="Simulation Source Network",
            category=Category.DRONE_SIMULATION,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.STARTUP,
            dependencies=["local_storage"],
            description="Simulated city surveillance camera and drone source registry for Phase 5 scenario readiness.",
            owner="backend/app/services/simulation_source_service.py",
            resource_profile=[Resource.FILE_IO, Resource.CPU_LIGHT],
            component_path="backend/app/services/simulation_source_service.py",
            metadata={
                "min_cameras": 12,
                "min_drones": 2,
                "writable_paths": ["runtime_state"],
            },
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="sim_scenario_engine",
            name="Simulation Scenario Engine",
            category=Category.DRONE_SIMULATION,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["simulation_source_network"],
            description="Deterministic crime scenario engine with step/auto run modes, observation generation, and alert promotion.",
            owner="backend/app/services/scenario_engine_service.py",
            resource_profile=[Resource.CPU_LIGHT, Resource.FILE_IO],
            component_path="backend/app/services/scenario_engine_service.py",
            metadata={
                "min_scenarios": 1,
                "required_scenario_ids": ["bank_robbery_demo"],
                "writable_paths": ["runtime_state/scenario_promotions"],
            },
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="visual_tracking_fusion",
            name="Visual Tracking and Fused Path",
            category=Category.DRONE_SIMULATION,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["sim_scenario_engine", "simulation_source_network"],
            description=(
                "Deterministic suspect path tracking, camera handoff chaining, "
                "DRONE-ALPHA route, and fused CCTV+drone observation track for "
                "command-center visualization."
            ),
            owner="backend/app/services/fused_path_service.py",
            resource_profile=[Resource.CPU_LIGHT, Resource.FILE_IO],
            component_path="backend/app/services/fused_path_service.py",
            metadata={
                "required_scenario_ids": ["bank_robbery_demo"],
                "min_suspect_waypoints": 5,
                "min_camera_handoffs": 5,
                "min_drone_waypoints": 4,
            },
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="drone_unified_state",
            name="Unified Drone Operational State",
            category=Category.DRONE_SIMULATION,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["simulation_source_network", "visual_tracking_fusion"],
            description=(
                "Merged operational snapshot per drone: registry status, scenario "
                "dispatch context, Phase 7 route lifecycle, and AirSim provider "
                "health. AirSim disconnected is non-fatal."
            ),
            owner="backend/app/services/drone_operational_state_service.py",
            resource_profile=[Resource.CPU_LIGHT],
            component_path="backend/app/services/drone_operational_state_service.py",
            metadata={
                "airsim_required": False,
                "registry_required": True,
                "phase": 8,
            },
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="exhibition_demo_workflow",
            name="Exhibition Demo Workflow",
            category=Category.DRONE_SIMULATION,
            criticality=Criticality.MISSION_CORE,
            activation_mode=Mode.ON_DEMAND,
            dependencies=[
                "sim_scenario_engine",
                "visual_tracking_fusion",
                "drone_unified_state",
                "alerts",
                "analytics",
            ],
            description=(
                "One-click exhibition demo controller: bank_robbery_demo orchestration, "
                "step/auto-run modes, operator snapshot, and runbook surface."
            ),
            owner="backend/app/services/exhibition_demo_service.py",
            resource_profile=[Resource.CPU_LIGHT, Resource.FILE_IO],
            component_path="backend/app/services/exhibition_demo_service.py",
            metadata={
                "scenario_id": "bank_robbery_demo",
                "airsim_required": False,
                "phase": 9,
            },
        ),
        CapabilityState.COLD,
        _cold_reason(),
    ),
    DefaultCapability(
        _descriptor(
            capability_id="llm_osint",
            name="LLM / OSINT",
            category=Category.LLM_OSINT,
            criticality=Criticality.EXTERNAL_DEPENDENT,
            activation_mode=Mode.ON_DEMAND,
            dependencies=["cases", "evidence"],
            description="Analyst-provided OSINT enrichment and source-grounded LLM report assistance.",
            owner="backend/app/services/llm_service.py",
            resource_profile=[Resource.EXTERNAL_SERVICE, Resource.NETWORK_IO, Resource.FILE_IO],
            config_key="llm_osint",
            component_path="backend/app/services/llm_service.py",
            metadata={
                "config_path": "configs/runtime/llm.yaml",
                "enabled_path": "llm.enabled",
                "required_env": ["OPENAI_API_KEY"],
            },
        ),
        CapabilityState.COLD,
        "Registered as an external-dependent core capability; provider verification awaits managed activation.",
    ),
)


def register_default_capabilities(registry: CapabilityRegistry | None = None) -> CapabilityRegistry:
    target = registry or get_capability_registry()
    for entry in DEFAULT_CAPABILITIES:
        existing = target.get_or_none(entry.descriptor.id)
        target.register(entry.descriptor)
        if existing is None:
            target.update_status(
                entry.descriptor.id,
                entry.initial_state,
                entry.initial_reason,
                health_score=1.0 if entry.initial_state == CapabilityState.READY else 0.7,
            )
    return target
